# Generated by Django 3.2.13 on 2022-06-22 00:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='save_excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='uploads/excel/')),
            ],
        ),
        migrations.CreateModel(
            name='TagNewTestcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCasetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tag', models.ManyToManyField(to='testcase.TagNewTestcase')),
            ],
        ),
        migrations.CreateModel(
            name='Teststep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('remark', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('modify_history', models.TextField(blank=True, null=True)),
                ('testcase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testcase.testcasetest')),
            ],
        ),
    ]
