# Generated by Django 3.2.13 on 2022-06-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasetest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.createproject'),
        ),
    ]
