# Generated by Django 3.2.13 on 2022-06-24 08:40

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcase', '0002_testcasetest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagnewtestcase',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcasetest',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcasetest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcasetest',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
