# Generated by Django 3.2.13 on 2022-06-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_auto_20220624_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasetest',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='testcasetest',
            name='project',
        ),
    ]
