# Generated by Django 3.2.13 on 2022-06-27 07:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_auto_20220627_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststep',
            name='condition',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teststep',
            name='remark',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
