# Generated by Django 3.2.13 on 2022-07-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0006_auto_20220705_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteststep',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalteststep',
            name='testcase',
        ),
        migrations.DeleteModel(
            name='HistoricalTestCasetest',
        ),
        migrations.DeleteModel(
            name='HistoricalTeststep',
        ),
    ]
