# Generated by Django 3.2.13 on 2022-06-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220629_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createproject',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='createproject',
            name='stop_date',
        ),
    ]
