# Generated by Django 3.2.13 on 2022-07-07 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_auto_20220629_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createproject',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
