# Generated by Django 3.2.13 on 2022-07-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0007_auto_20220706_1727'),
        ('project', '0004_auto_20220707_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='tag',
            field=models.ManyToManyField(to='testcase.TagNewTestcase'),
        ),
    ]
