# Generated by Django 3.2.13 on 2022-07-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_createproject_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
