# Generated by Django 3.2.13 on 2022-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20220707_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
