# Generated by Django 3.2.13 on 2022-07-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_createproject_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
