# Generated by Django 3.2.13 on 2022-06-22 00:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseforTestplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('tag', models.ManyToManyField(to='testcase.TagNewTestcase')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('assign', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_activate', models.BooleanField(default=False)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeststepforTestplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('actual_outcome', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(default='Incomplete', max_length=100)),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('remark', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('modify_history', models.TextField(blank=True, null=True)),
                ('testcase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testplan.testcasefortestplan')),
            ],
        ),
        migrations.AddField(
            model_name='testcasefortestplan',
            name='testplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testplan.testplan_test'),
        ),
    ]
