# Generated by Django 3.2.13 on 2022-09-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestrun',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=100),
        ),
    ]
