# Generated by Django 3.2.13 on 2022-09-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0002_auto_20220922_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='creator',
        ),
    ]
