# Generated by Django 3.2.13 on 2022-07-07 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testplan', '0002_testplan_test_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan_test',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_set_testplan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testplan_test',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_set_testplan', to=settings.AUTH_USER_MODEL),
        ),
    ]
