# Generated by Django 3.2.13 on 2022-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0007_auto_20220706_1727'),
        ('testplan', '0003_auto_20220707_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan_test',
            name='tag',
            field=models.ManyToManyField(to='testcase.TagNewTestcase'),
        ),
    ]
