# Generated by Django 3.2.13 on 2022-10-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0003_auto_20220922_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testplan_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testplan.testplan')),
                ('testplan_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testplan.testplan_group')),
            ],
        ),
    ]
