# Generated by Django 3.2.13 on 2022-07-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0005_auto_20220715_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan_test',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
